security:
    # Encoders pour les utilisateurs
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Les utilisateurs proviennent de la base de données
    providers:
        # Provider utilisant l'entité User
        app_user_provider:
            entity:
                class: App\Domain\Entity\User
                property: email

    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall pour l'authentification principale
        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Infrastructure\Security\LoginFormAuthenticator
            custom_authenticators:
                - App\Infrastructure\Security\LoginFormAuthenticator
            form_login:
                enable_csrf: true
                login_path: app_login
                check_path: app_login
                username_parameter: username
                password_parameter: password
                csrf_token_id: authenticate
                always_use_default_target_path: false
                default_target_path: /
            logout:
                path: app_logout
                target: /

    # Configuration des accès par rôle
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }